"""For application progress_field changed to nullable=false

Revision ID: 0da6831aadb6
Revises: 2fedf2b5f8c6
Create Date: 2025-10-29 14:26:43.191327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as psql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da6831aadb6'
down_revision: Union[str, Sequence[str], None] = '2fedf2b5f8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'progress_status',
               existing_type=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'REJECTED', 'HIRED', name='progressstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'progress_status',
               existing_type=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'REJECTED', 'HIRED', name='progressstatus'),
               nullable=True)
    # ### end Alembic commands ###
