"""Edited the s3_path nullable false to true

Revision ID: 2289f9bac37b
Revises: 638708e3cb42
Create Date: 2025-09-13 00:25:55.402773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as psql


# revision identifiers, used by Alembic.
revision: str = '2289f9bac37b'
down_revision: Union[str, Sequence[str], None] = '638708e3cb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 's3_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 's3_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
