"""Add progress status for the application

Revision ID: 2fedf2b5f8c6
Revises: 118a026dc580
Create Date: 2025-10-29 14:16:44.420172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as psql


# revision identifiers, used by Alembic.
revision: str = '2fedf2b5f8c6'
down_revision: Union[str, Sequence[str], None] = '118a026dc580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('progress_status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'REJECTED', 'HIRED', name='progressstatus'), nullable=True))
    op.alter_column('applications', 'id',
               existing_type=sa.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'id',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text("nextval('applications_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('applications', 'progress_status')
    # ### end Alembic commands ###
