"""Add embeded values and improved the data types

Revision ID: 45e62b2520a9
Revises: 92b7714d1275
Create Date: 2025-09-28 14:12:38.619115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "45e62b2520a9"
down_revision: Union[str, Sequence[str], None] = "92b7714d1275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Drop dependent objects in safe order (if present in this DB)
    #    Note: We intentionally do NOT drop the "users" table to avoid cross-service disruption.
    op.drop_index(op.f("idx_job_posts_deleted_at"), table_name="job_posts")
    op.drop_table("job_posts")

    # 2) Ensure pgvector extension exists before adding vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 3) Create ENUM type explicitly to avoid "type does not exist"
    bind = op.get_bind()
    seniority_enum = sa.Enum(
        "INTERN",
        "JUNIOR",
        "MID",
        "SENIOR",
        name="senioritylevel",
    )
    seniority_enum.create(bind, checkfirst=True)

    # 4) Add columns using created ENUM and Vector types
    op.add_column(
        "applications",
        sa.Column("seniority_level", seniority_enum, nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("embedded_description", Vector(3072), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("embedded_requirements", Vector(3072), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("embedded_responsibility", Vector(3072), nullable=True),
    )

    # 5) created_at should be NOT NULL
    op.alter_column(
        "applications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )

    # 6) Replace embedded_value JSON with Vector; drop and re-add to avoid cast issues
    op.drop_column("applications", "embedded_value")
    op.add_column(
        "applications",
        sa.Column("embedded_value", Vector(3072), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse embedded_value: drop Vector and restore JSON
    op.drop_column("applications", "embedded_value")
    op.add_column(
        "applications",
        sa.Column(
            "embedded_value", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "applications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("applications", "embedded_responsibility")
    op.drop_column("applications", "embedded_requirements")
    op.drop_column("applications", "embedded_description")
    op.drop_column("applications", "seniority_level")

    # Drop ENUM type if exists
    bind = op.get_bind()
    seniority_enum = sa.Enum(
        "INTERN",
        "JUNIOR",
        "MID",
        "SENIOR",
        name="senioritylevel",
    )
    seniority_enum.drop(bind, checkfirst=True)
    # Recreate job_posts (users table recreation omitted intentionally to avoid conflicts)
    op.create_table(
        "job_posts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deadline",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("requirements", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "responsibilities",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "description_embedding", Vector(3072), autoincrement=False, nullable=True
        ),
        sa.Column(
            "requirements_embedding", Vector(3072), autoincrement=False, nullable=True
        ),
        sa.Column(
            "responsibilities_embedding",
            Vector(3072),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_job_posts"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("job_posts_pkey")),
    )
    op.create_index(
        op.f("idx_job_posts_deleted_at"), "job_posts", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###
