"""Addedd failed_reason in Application Model

Revision ID: ce718f2682c8
Revises: 2289f9bac37b
Create Date: 2025-09-13 01:39:13.618161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as psql


# revision identifiers, used by Alembic.
revision: str = 'ce718f2682c8'
down_revision: Union[str, Sequence[str], None] = '2289f9bac37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('failed_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'failed_reason')
    # ### end Alembic commands ###
