"""Add phone_number to Application Table

Revision ID: ff6428f05769
Revises: 0da6831aadb6
Create Date: 2025-10-30 17:39:38.800730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6428f05769'
down_revision: Union[str, Sequence[str], None] = '0da6831aadb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Add the column with a server default so existing rows get a value
    op.add_column(
        'applications',
        sa.Column('phone_number', sa.String(), nullable=False, server_default='0000000000')
    )
    # 2) Drop the server default to avoid populating future rows implicitly at the DB level
    op.alter_column('applications', 'phone_number', server_default=None)
    op.alter_column('applications', 'job_post_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'job_post_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('applications', 'phone_number')
    # ### end Alembic commands ###
